# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8e153c388130f74e990df5f29350491da86d667b59e55b5a189769862eb7b299095f51738f237ac2edd174b3e6e5690092c6bf0e27afa6e588abcba5b2d98d5

test:
  secret_key_base: 953442f8304aeade5ead01a64a497bc57a6e1f1ed41c0fb4d2edc9154433d2830412add520cdee8c86819dc30a72372dc101379a1699d9283f834202aa7f1195

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
